* Initial startup
** Debug traceback
#+BEGIN_SRC emacs-lisp
  (setq debug-on-error t)
#+END_SRC
** Daemon
#+BEGIN_SRC emacs-lisp
  ;; start emacs as daemon for emacsclient functionality.
  (server-start)
#+END_SRC
* Terminal
** setting default shell to bash
#+BEGIN_SRC emacs-lisp
  ;; this calls ansi-term with bash as default shell
  (defvar my-term-shell "/bin/bash")
  (defadvice ansi-term (before force-bash)
    (interactive (list my-term-shell)))
  (ad-activate 'ansi-term)
#+END_SRC

* General preferences
** shorten yes-or-no key press
#+BEGIN_SRC emacs-lisp
  ;; change yes or no answer to y or n to reduce key presses
  (defalias 'yes-or-no-p 'y-or-n-p)
#+END_SRC

** line by line scroll when edging screen
#+BEGIN_SRC emacs-lisp
  (setq scroll-conservatively 100)
#+END_SRC

** disable audio bell
#+BEGIN_SRC emacs-lisp
  (setq ring-bell-function 'ignore)
#+END_SRC

** disable gui elements to maximize screen
#+BEGIN_SRC emacs-lisp
  (tool-bar-mode -1)
  (menu-bar-mode -1)
  (scroll-bar-mode -1)
#+END_SRC

** diable auto-save and backups
#+BEGIN_SRC emacs-lisp
  ;; disable backup files and auto-saving
  (setq make-backup-file nil)
  (setq auto-save-default nil)
#+END_SRC

** general shortcuts
#+BEGIN_SRC emacs-lisp
  ;; remove suspend emacs shortcut
  (global-unset-key (kbd "C-z"))

  ;; shortcut to open up ansi-term
  (global-set-key (kbd "C-c C-<return>") 'ansi-term)
#+END_SRC

** scroll margin for easier reading
#+BEGIN_SRC emacs-lisp
  (setq scroll-margin 7)
#+END_SRC

** subword
#+BEGIN_SRC emacs-lisp
  ;; correctly treats camel case as separate words
  (global-subword-mode 1)
#+END_SRC
** electric typing
#+BEGIN_SRC emacs-lisp
  ;; enable auto pairing for some types...
  (setq electric-pair-pairs '(
                              (?\( . ?\))
                              (?\[ . ?\])
                              (?\{ . ?\})
                              ))
  (electric-pair-mode t)
#+END_SRC

** paren
#+BEGIN_SRC emacs-lisp
  (show-paren-mode 1)
#+END_SRC

** prettify symbol
#+BEGIN_SRC emacs-lisp
  (when window-system (global-prettify-symbols-mode t))
#+END_SRC
** highlight line
#+BEGIN_SRC emacs-lisp
  (when window-system (add-hook 'prog-mode-hook 'hl-line-mode))
#+END_SRC
** Spell check
#+BEGIN_SRC emacs-lisp
  (add-hook 'text-mode-hook 'flyspell-mode)
#+END_SRC
* Modeline
** Settings
#+BEGIN_SRC emacs-lisp
  (setq line-number-mode t)
  (setq column-number-mode t)
#+END_SRC
* Org mode
** basic config
#+BEGIN_SRC emacs-lisp
  ;; edit source in current window... no new tab
  (setq org-src-window-setup 'current-window)

  ;; visually indent subheadings to improve readability
  (add-hook 'org-mode-hook 'org-indent-mode)

  ;; makes src blocks easier to read
  (setq org-src-fontify-natively t
        org-src-tab-acts-natively t)

  ;; change ellipsis for org
  (setq org-ellipsis "⤵")

  ;; make sure to do time stamp when done
  (setq org-log-done 'time)
#+END_SRC
** templates
#+BEGIN_SRC emacs-lisp
  (add-to-list 'org-structure-template-alist
	       '("el" "#+BEGIN_SRC emacs-lisp\n?\n#+END_SRC"))
#+END_SRC
** Exports
#+BEGIN_SRC emacs-lisp
  (use-package ox-twbs
    :ensure t)
#+END_SRC
** notes
#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "C-c o")
                  (lambda ()
                    (interactive)
                    (find-file "~/Org/organizer.org")))
#+END_SRC
** Org-bullets
#+BEGIN_SRC emacs-lisp
  (use-package org-bullets
    :ensure t
    :config
    (add-hook 'org-mode-hook (lambda () (org-bullets-mode))))

#+END_SRC
** Agenda
#+BEGIN_SRC emacs-lisp
  (setq org-agenda-files (list "~/Org/organizer.org"
                               ))
#+END_SRC
* Buffers
** Set default buffer manager to ibuffer
#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "C-x C-b") 'ibuffer)
#+END_SRC
** Set always kill current buffer
No more confirmation of which buffer to kill after C-x k... Use ibuffer more sophistiated killings
#+BEGIN_SRC emacs-lisp
  (defun kill-current-buffer ()
    "Kills the current buffer."
    (interactive)
    (kill-buffer (current-buffer)))
  (global-set-key (kbd "C-x k") 'kill-current-buffer)
#+END_SRC
* Dashboard
A package that offers a much better startup screen, displaying recent files.
** Initialize
#+BEGIN_SRC emacs-lisp
  (use-package dashboard
    :ensure t
    :config
    (dashboard-setup-startup-hook)
    (setq dashboard-items '((recents . 5)
                            (projects . 5)
                            (agenda . 5)))
    (setq dashboard-startup-banner "~/.emacs.d/img/emacs.png")
    (setq dashboard-banner-logo-title
          (format "Emacs ready in %.2f seconds with %d garbage collections."
                  (float-time (time-subtract after-init-time before-init-time)) gcs-done)))
#+END_SRC
* Nlinum-relative
Relative line numbers with jit-lock
** Initialize
#+BEGIN_SRC emacs-lisp
  (use-package nlinum-relative
    :ensure t
    :config
    (nlinum-relative-setup-evil)
    (add-hook 'prog-mode-hook 'nlinum-relative-mode))
#+END_SRC
* IDO-vertical
Used to fill out some of the additional selections that doesn't use ivy
** Initialize
#+BEGIN_SRC emacs-lisp
  (use-package ido-vertical-mode
    :ensure t
    :init (ido-vertical-mode 1))
  ;; bind keys for moving up and down
  (setq ido-vertical-define-keys 'C-n-and-C-p-only)
#+END_SRC
* Smex
Mainly used for ivy "most recent" function
** Initialize
#+BEGIN_SRC emacs-lisp
  (use-package smex
    :ensure t
    :init (smex-initialize))
#+END_SRC
* Ivy
Completion framework
** Initialize
#+BEGIN_SRC emacs-lisp
  (use-package ivy
    :ensure t
    :config
    (ivy-mode 1)
    (setq ivy-use-virtual-buffers t)
    (setq enable-recursive-minibuffers t))
  (global-set-key (kbd "C-c C-r") 'ivy-resume)
#+END_SRC
* Swiper
** a better search
#+BEGIN_SRC emacs-lisp
  (use-package swiper
    :ensure t
    :bind ("C-s" . swiper))
#+END_SRC

* Counsel
Extension to functionality of ivy and swiper commands
** Initialize
#+BEGIN_SRC emacs-lisp
  (use-package counsel
    :ensure t
    :config (counsel-mode))
#+END_SRC
* Avy
A package that allows you to go to any character on screen.
** Initialize
#+BEGIN_SRC emacs-lisp
  (use-package avy
    :ensure t
    :bind ("M-s" . avy-goto-char))
#+END_SRC
* Config
Some custom shortcuts to reload main config file.
** reload config file
#+BEGIN_SRC emacs-lisp
  (defun config-reload ()
    (interactive)
    (load-file "~/.emacs.d/init.el"))
  (global-set-key (kbd "C-c r") 'config-reload)
#+END_SRC
* Rainbow
A package that changes the background colour to the corresponding hex code that is under it. 
** Initialize
#+BEGIN_SRC emacs-lisp
  (use-package rainbow-mode
    :ensure t
    :init (add-hook 'prog-mode-hook 'rainbow-mode))

#+END_SRC
* Rainbow Delimiters
A package that colours parenthesis with matching depth. Very useful for lisp!
#+BEGIN_SRC emacs-lisp
  (use-package rainbow-delimiters
    :ensure t
    :init
    (add-hook 'prog-mode-hook #'rainbow-delimiters-mode))
#+END_SRC
* Window management
Some custom tweaks to enhance the experience with window manipulation.
** Override window splitting functions... move cursor correspondingly when opening splits
#+BEGIN_SRC emacs-lisp
  ;; split window horizontally and let cursor position
  (defun split-and-follow-horizontally ()
    (interactive)
    (split-window-below)
    (balance-windows)
    (other-window 1))
  (global-set-key (kbd "C-x 2") 'split-and-follow-horizontally)

  ;; split window vertically and toggle cursor position
  (defun split-and-follow-vertically ()
    (interactive)
    (split-window-right)
    (balance-windows)
    (other-window 1))
  (global-set-key (kbd "C-x 3") 'split-and-follow-vertically)
#+END_SRC
* Editing
** Line transpose
#+BEGIN_SRC emacs-lisp
  (defun move-text-internal (arg)
     (cond
      ((and mark-active transient-mark-mode)
       (if (> (point) (mark))
              (exchange-point-and-mark))
       (let ((column (current-column))
                (text (delete-and-extract-region (point) (mark))))
         (forward-line arg)
         (move-to-column column t)
         (set-mark (point))
         (insert text)
         (exchange-point-and-mark)
         (setq deactivate-mark nil)))
      (t
       (beginning-of-line)
       (when (or (> arg 0) (not (bobp)))
         (forward-line)
         (when (or (< arg 0) (not (eobp)))
              (transpose-lines arg))
         (forward-line -1)))))

  (defun move-text-down (arg)
     "Move region (transient-mark-mode active) or current line
    arg lines down."
     (interactive "*p")
     (move-text-internal arg))

  (defun move-text-up (arg)
     "Move region (transient-mark-mode active) or current line
    arg lines up."
     (interactive "*p")
     (move-text-internal (- arg)))

  (global-set-key [\M-\S-up] 'move-text-up)
  (global-set-key [\M-\S-down] 'move-text-down)
#+END_SRC
* Company mode
A package for auto-completion, note that this still requires manually adding back-ends.
** Initialize
#+BEGIN_SRC emacs-lisp
  ;; install company mode
  (use-package company
    :ensure t
    :bind (("C-c /" . company-complete))


  :config
    (setq company-idle-delay 0)
    (setq company-minimum-prefix-length 3)
    :init
    (add-hook 'after-init-hook 'global-company-mode))

  ;; tooltips
  (use-package company-quickhelp
    :ensure t
    :config
    (setq company-quickhelp-delay 1))

  (require 'company-quickhelp)
  (company-quickhelp-mode)

  ;; python backend
  (use-package company-jedi
    :ensure t
    :config
      (require 'company)
      (add-to-list 'company-backends 'company-jedi))

  (defun python-mode-company-init ()
    (setq-local company-backends '((company-jedi
                                    company-etags
                                    company-dabbrev-code))))
  (use-package company-jedi
    :ensure t
    :config
      (require 'company)
      (add-hook 'python-mode-hook 'python-mode-company-init))

  ;; bash backend
  (defun shell-mode-company-init ()
    (setq-local company-backends '((company-shell
                                    company-shell-env
                                    company-etags
                                    company-dabbrev-code))))

  (use-package company-shell
    :ensure t
    :config
      (require 'company)
      (add-hook 'sh-mode-hook 'shell-mode-company-init))
#+END_SRC
* Spacemacs theme
** Initialize
#+BEGIN_SRC emacs-lisp
  (use-package spacemacs-common
    :ensure spacemacs-theme
    :config (load-theme 'spacemacs-dark t))
#+END_SRC
* Popup kill ring
A package that adds a popup menu for kill ring selections
** Initialize
#+BEGIN_SRC emacs-lisp
  (use-package popup-kill-ring
    :ensure t
    :bind ("M-y" . popup-kill-ring))
#+END_SRC

* Expand-region
A package that allows you to expand selection from current position.
** Initialize
#+BEGIN_SRC emacs-lisp
  (use-package expand-region
    :ensure t
    :bind ("C-q" . er/expand-region))
#+END_SRC

* Sudo edit
A package that allow you to edit remote files and local files that require additional sudo permission.
** Initialize
#+BEGIN_SRC emacs-lisp
  (use-package sudo-edit
    :ensure t
    :bind ("C-c e" . sudo-edit))
#+END_SRC

* Yasnippet
A package that allows you to add and use snippets.
** Initialize
#+BEGIN_SRC emacs-lisp
  (use-package yasnippet
    :ensure t
    :config
    (use-package yasnippet-snippets
      :ensure t)
    (yas-reload-all))
#+END_SRC

** Hooks
#+BEGIN_SRC emacs-lisp

  ;; manually add required hooks... avoid global-mode
  (add-hook 'python-mode-hook 'yas-minor-mode)
  (add-hook 'sh-mode-hook 'yas-minor-mode)
#+END_SRC

* Flycheck
A package that enables syntax checking for programming
** Initialize
#+BEGIN_SRC emacs-lisp
  (use-package flycheck
    :ensure t)
#+END_SRC

** Hooks
#+BEGIN_SRC emacs-lisp
  (add-hook 'python-mode-hook 'flycheck-mode)
  (add-hook 'sh-mode-hook 'flycheck-mode)
#+END_SRC

* ZZZ
An upgraded zap-to-char package that allows you to delete to a selected character.
** Initialize
#+BEGIN_SRC emacs-lisp
  (use-package zzz-to-char
    :ensure t
    :bind ("M-z" . zzz-up-to-char))
#+END_SRC

* Magit
A package that integrates git with more intuitive controls
** Initialize
#+BEGIN_SRC emacs-lisp
  (use-package magit
    :ensure t)
#+END_SRC

* Projectile
** Initialize
#+BEGIN_SRC emacs-lisp
  (use-package projectile
    :ensure t
    :init
    (projectile-mode 1))
  (define-key projectile-mode-map (kbd "C-c p") 'projectile-command-map)
#+END_SRC
* Neotree
** Initialize
#+BEGIN_SRC emacs-lisp
  (use-package neotree
    :ensure t
    :bind ([f8] . neotree-toggle))
#+END_SRC

* Buffer-move
A package that allows you to move windows around
** Initialize
#+BEGIN_SRC emacs-lisp
  (use-package buffer-move
    :ensure t)

  (require 'evil-leader)
  (global-evil-leader-mode)
  (evil-leader/set-key
    "<SPC> h" 'buf-move-left
    "<SPC> j" 'buf-move-down
    "<SPC> k" 'buf-move-up
    "<SPC> l" 'buf-move-right
    )
#+END_SRC

* Undo Tree
A package that gives you a visual history of undos
** Initialize
#+BEGIN_SRC emacs-lisp
  (use-package undo-tree
    :ensure t
    :init (global-undo-tree-mode))
#+END_SRC

* Git gutter
A live visual on git changes
** Initialize
#+BEGIN_SRC emacs-lisp
  (use-package git-gutter
    :ensure t)
  (global-git-gutter-mode +1)
#+END_SRC

* Evil leader
Leader key for evil mode
** Initialize
#+BEGIN_SRC emacs-lisp
  (use-package evil-leader
    :ensure t
    )
  (require 'evil-leader)
  (global-evil-leader-mode)
  (evil-leader/set-leader "<SPC>")
#+END_SRC

* Evil mode
An extensive vi layer for better editing experience.
** Initialize
#+BEGIN_SRC emacs-lisp
  (use-package evil
    :ensure t
    :bind ("C-c b t" . evil-switch-to-windows-last-buffer)
    :init
    (setq evil-normal-state-cursor '("orchid")
          evil-emacs-state-cursor '("light blue")
          evil-insert-state-cursor '("SpringGreen" bar)
          evil-replace-state-cursor '("chocolate1" hbar)
          evil-visual-state-cursor '("gray")))
  (require 'evil)
  (evil-mode 1)
  ;; remap C-u for vim-like functionality.
  (define-key evil-normal-state-map (kbd "C-u") 'evil-scroll-up)
  (define-key evil-visual-state-map (kbd "C-u") 'evil-scroll-up)
  (define-key evil-insert-state-map (kbd "C-u")
    (lambda ()
      (interactive)
      (evil-delete (point-at-bol) (point))))
#+END_SRC
* Evil-mc
Multi-cursors for evil mode
** Initialize
#+BEGIN_SRC emacs-lisp
  (use-package evil-mc
    :ensure t)
  (global-evil-mc-mode 1)
#+END_SRC

* Evil-nerd-commenter
Commenting in evil mode
** Initialize
#+BEGIN_SRC emacs-lisp
  (use-package evil-nerd-commenter
    :ensure t)

  ;; Vim key bindings
  (require 'evil-leader)
  (global-evil-leader-mode)
  (evil-leader/set-key
    "ci" 'evilnc-comment-or-uncomment-lines
    "cl" 'evilnc-quick-comment-or-uncomment-to-the-line
    "ll" 'evilnc-quick-comment-or-uncomment-to-the-line
    "cc" 'evilnc-copy-and-comment-lines
    "cp" 'evilnc-comment-or-uncomment-paragraphs
    "cr" 'comment-or-uncomment-region
    "cv" 'evilnc-toggle-invert-comment-line-by-line
    "."  'evilnc-copy-and-comment-operator
    "\\" 'evilnc-comment-operator ; if you prefer backslash key
  )
#+END_SRC

* General Evil-leader shortcuts
** Window movement
#+BEGIN_SRC emacs-lisp
  (require 'evil-leader)
  (global-evil-leader-mode)
  (evil-leader/set-key
    "h" 'previous-buffer
    "l" 'next-buffer
    "f h" 'windmove-left
    "f j" 'windmove-down
    "f k" 'windmove-up
    "f l" 'windmove-right
    )
#+END_SRC
* Diminish
Hide some of the minor modes taking up space on the modeline
** Initialize
#+BEGIN_SRC emacs-lisp
  (use-package diminish
    :ensure
    :init
    (diminish 'beacon-mode)
    (diminish 'rainbow-mode)
    (diminish 'which-key-mode)
    (diminish 'undo-tree-mode)
    (diminish 'git-gutter-mode)
    (diminish 'subword-mode)
    (diminish 'org-indent-mode)
    (diminish 'ivy-mode))
#+END_SRC

* Eyebrowse
Workspace setup
** initialize
#+BEGIN_SRC emacs-lisp
  (use-package eyebrowse
    :ensure t
    :config (progn
              (define-key eyebrowse-mode-map (kbd "C-1") 'eyebrowse-switch-to-window-config-1)
              (define-key eyebrowse-mode-map (kbd "C-2") 'eyebrowse-switch-to-window-config-2)
              (define-key eyebrowse-mode-map (kbd "C-3") 'eyebrowse-switch-to-window-config-3)
              (define-key eyebrowse-mode-map (kbd "C-4") 'eyebrowse-switch-to-window-config-4)
              (define-key eyebrowse-mode-map (kbd "C-5") 'eyebrowse-switch-to-window-config-5)
              ))
  (require 'eyebrowse)
  (eyebrowse-mode t)
#+END_SRC

* Flymd
A package for markdown live preview
** Initialize
#+BEGIN_SRC emacs-lisp
  (use-package flymd
    :ensure t)
#+END_SRC

* Quick run
A package that allows you to quickly execute files of many languages.
** Initialize
#+BEGIN_SRC emacs-lisp
  (use-package quickrun
    :ensure t)
#+END_SRC
* Ace-window
A package that allows you to switch focus between windows quickly
** Initialize
#+BEGIN_SRC emacs-lisp
  (use-package ace-window
    :ensure t
    :bind
    ("C-x o" . 'ace-window)
    ("C-c s" . 'ace-swap-window))
#+END_SRC
